title: Mechanical Tsar
email: dmitry@eveel.ru
description: Mechanical Tsar is a crowdsourcing engine for mechanized labor.
baseurl: ""
url: "http://mtsar.nlpub.org"
twitter_username: nlpub
github_username: mtsar
markdown: kramdown
exclude:
  - Gemfile*
safe: true
timezone: Asia/Yekaterinburg
encoding: UTF-8
